### ISSUE TITLE
The environment you requested was unavailable - Invalid osVersion for appium

### ISSUE THREAD

**Issue by kotlav** [appetizeio/appium-samples#2]
I have tried to run an appium script written node. I am getting the above error. An advice will help. Here's the snippet of the script: 

<>
var wd = require('wd');
var request = require('request');
var Promise = require('bluebird'); // jshint ignore:line
var fs = require('fs');

var filepath = 'outputs/';
fs.mkdir(filepath, function(ignored) {});

var apiToken = 'token'; // your API token from https://appetize.io/docs#request-api-token
var deviceType = 'iphone6s'; // iphone4s, iphone5s, iphone6s, iphone6splus, iphone7, iphone7plus, ipadair2
var publicKey = 'xyz'; // replace with your own publicKey after uploading through website or API
var osVersion = '10.0'; // also supports 10.2, 10.1, 10.0
var proxy = 'intercept'; // false for no proxy, or specify your own with http://proxy-example.com:port
var params = {
    hello: 'world',
    userId: 123
}; // optional data to pass to app at launch
var automationName = 'Appium';

var driver = wd.remote('https://' + apiToken + '@appium.appetize.io/wd/hub', 'promiseChain');
console.log('https://' + apiToken + '@appium.appetize.io/wd/hub')

console.log('starting session');
driver.init({
    device: deviceType,
    publicKey: publicKey,
    osVersion: osVersion,
    proxy: proxy,
    automationName: 'XCUITest',
    platformName: 'iOS'
}).delay(5000)
//.then(takeScreenshot)
.then(function() {
    console.log('tapping element');
    return driver.elementByXPath('//XCUIElementTypeButton[@name="Go"]').click().delay(2000);
})

......
....
<>

The error is

Error occured in promise
{ Error: [init({"device":"iphone6s","publicKey":"vy1rppzm2u82nzzt6e8y06h5m8","osVersion":"10.0","proxy":"intercept","automationName":"XCUITest","platformName":"iOS"})] The environment you requested was unavailable.
    at /Users/kotla/Documents/Learnings/appium/appetize_appium_samples/node.js/node_modules/wd/lib/webdriver.js:134:15
    at Request._callback (/Users/kotla/Documents/Learnings/appium/appetize_appium_samples/node.js/node_modules/wd/lib/http-utils.js:88:7)
    at Request.self.callback (/Users/kotla/Documents/Learnings/appium/appetize_appium_samples/node.js/node_modules/wd/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/kotla/Documents/Learnings/appium/appetize_appium_samples/node.js/node_modules/wd/node_modules/request/request.js:1081:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/kotla/Documents/Learnings/appium/appetize_appium_samples/node.js/node_modules/wd/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) data: 'Invalid osVersion for appium' 

> `}`

Thanks!

**Comment by BenAychh** [comment]
Anybody? Is this a service you offer anymore?

**Comment by snyderj** [comment]
Hi Ben, apologies but this is no longer offered as part of the Appetize.io service.
